# Publish scans from best pose at a max of 10 Hz 
tf_broadcast: false
use_map_topic: true
selective_resampling: false
transform_tolerance: 0.2
gui_publish_rate: 10.0
laser_max_beams: 30
min_particles: 80
max_particles: 800
kld_err: 0.05
kld_z: 0.99
odom_model_type: diff-corrected
odom_alpha1: 0.005
odom_alpha2: 0.05
# translation std dev, m 
odom_alpha3: 0.010
odom_alpha4: 0.005
odom_alpha5: 0.003
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_lambda_short: 0.1
laser_model_type: likelihood_field #beam
laser_likelihood_max_dist: 2.0
update_min_d: 0.2
update_min_a: 0.5
odom_frame_id: odom
base_frame_id: base_footprint
global_frame_id: map
resample_interval: 1
transform_tolerance: 0.1
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.0

initial_pose_x: $(arg x_init_pose)
initial_pose_y: $(arg y_init_pose)
initial_pose_z: $(arg z_init_pose)
initial_pose_a: 0.0
