map_frame: map
base_frame: base_footprint
odom_frame: odom
map_update_interval: 5.0
maxUrange: 5.0
maxRange: 6.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.1
iterations: 15
lsigma: 0.075
ogain: 3.0
lskip: 0
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 0.15
angularUpdate: 0.3
temporalUpdate: 3.0
resampleThreshold: 0.25
particles: 10
xmin: -15.0
ymin: -15.0
xmax: 15.0
ymax: 15.0
delta: 0.025
llsamplerange: 0.02
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
occ_thresh: 0.25
minimumScore: 1000
